CREATE LOGIN [YAVAY]
    WITH PASSWORD = N'o5|rjrCodxOejizegcTdzbt{msFT7_&#$!~<~|QwO^Gjpxgj', SID = 0x97644448DB3BFA47B3AE41AFA25631D4, DEFAULT_DATABASE = [BalancePlatform], DEFAULT_LANGUAGE = [us_english], CHECK_EXPIRATION = ON;

